name: Run Simulation Tests

on:
  push:
    branches:
      - '*'        # Trigger on push to any branch
  pull_request:
    branches:
      - '*'        # Trigger on pull request to any branch

jobs:
  sil:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code with submodules
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      # Install dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest swig

      # Install CMake and build tools
      - name: Install CMake and build tools
        run: |
          sudo apt-get update
          sudo apt-get install cmake gcc g++ python3-dev -y

      # Configure the project
      - name: Configure project with CMake
        run: |
          mkdir examples/build
          cd examples/build
          cmake ..

      # Build the project
      - name: Build the project
        run: |
          cd examples/build
          make

      # Run the tests
      - name: Run simulation tests
        run: |
          cd examples/test
          sh run_tests.sh
